name: Test
on:
  push:
    branches: [master]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: 17

      - name: Test
        run: sbt test

  publish:
    needs: [build]
    if: (github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))) || 
      (github.event_name == 'pull_request' &&  contains(github.event.pull_request.labels.*.name, 'publish'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: 8
      - name: Cache SBT
        uses: coursier/cache-action@v6
      - name: Publish
        run: sbt version "git status" ci-release "git status"
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
